version: "3.1"
services:
  telegraf:
    image: telegraf
    container_name: demo_telegraf
    restart: always
    env_file:
      - 'env/telegraf'
    volumes:
      - ./telegraf/:/etc/telegraf/:z
      - ./mibs/:/usr/share/snmp/mibs/:z
    command: --config-directory /etc/telegraf/telegraf.d --config /etc/telegraf/telegraf.conf   

  grafana:
    image: grafana/grafana:latest
    container_name: demo_grafana
    ports:
      - "3000:3000"
    user: "0"

  influxdb:
    image: influxdb:latest
    container_name: demo_influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env/influxdb'
